language: csharp
solution: Gerencianet.sln
install:
  - nuget restore Gerencianet.SDK.sln || true
script:
  - xbuild /tv:4.0 /p:Configuration=Release Gerencianet.SDK.sln
  - mono ./packages/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Gerencianet.SDK.Tests/bin/Release/Gerencianet.SDK.Tests.dll